# Generated by Django 5.1.2 on 2024-11-05 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text"), ("html", "Html")],
                        help_text="The type of the message (HTML or Text)",
                        max_length=10,
                        verbose_name="Email Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the message template",
                        max_length=200,
                        verbose_name="Message Title",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The body of the message template",
                        verbose_name="Message Body",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="The account that owns this message template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags associated with this message template",
                        related_name="message_templates",
                        to="tag.tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
