services:
  postgres:
    image: postgres:17.0
    env_file:
      - .postgres.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.6
    volumes:
      - ./docker/redis/data:/data
  reactimail:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: ./docker/reactimail/Dockerfile
    env_file:
      - .reactimail.env
    ports:
      - "18000:8000"
    volumes:
      - '.:/opt/reactimail'
    command: sleep infinity
    # command: python reactimail/manage.py runserver 0.0.0.0:8000
